services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  DailyCheckinBundle\Controller\:
    resource: '../../Controller/'
  DailyCheckinBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  DailyCheckinBundle\Procedure\:
    resource: '../../Procedure/'
  DailyCheckinBundle\Repository\:
    resource: '../../Repository/'
  DailyCheckinBundle\Service\:
    resource: '../../Service/'
  DailyCheckinBundle\AdminMenu: ~

